# Generated by Django 6.1.1 on 2026-09-30 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('ordenes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='ordenitem',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ordenes.orden', verbose_name='Orden Asociada'),
        ),
        migrations.AddField(
            model_name='ordenitem',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='en_ordenes', to='catalogo.producto', verbose_name='Producto Comprado'),
        ),
        migrations.AddConstraint(
            model_name='ordenitem',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='chk_orden_item_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='ordenitem',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0)), name='chk_orden_item_precio_no_negativo'),
        ),
    ]
