# Generated by Django 6.1.1 on 2026-10-02 00:35

from django.db import migrations
from decimal import Decimal


def restaurar_totales(apps, schema_editor):
    """Una reversión reconstruye el agregado desde los precios históricos."""
    Orden = apps.get_model('ordenes', 'Orden')
    Item = apps.get_model('ordenes', 'OrdenItem')
    alias = schema_editor.connection.alias
    for orden in Orden.objects.using(alias).iterator():
        orden.total = sum((item.precio_unitario * item.cantidad for item in
                           Item.objects.using(alias).filter(orden_id=orden.pk)), Decimal('0.00'))
        orden.save(using=alias, update_fields=['total'])


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, restaurar_totales),
        migrations.RemoveField(
            model_name='orden',
            name='total',
        ),
    ]
