# Generated by Django 6.1.1 on 2026-10-02 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_remove_producto_especificaciones_and_more'),
        ('ordenes', '0003_remove_orden_total'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ordenitem',
            constraint=models.UniqueConstraint(fields=('orden', 'producto'), name='unique_orden_producto'),
        ),
    ]
