# Generated by Django 6.1.1 on 2026-09-30 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carro', '0001_initial'),
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrito', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Propietario'),
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carro.carrito', verbose_name='Carro Asociado'),
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_carros', to='catalogo.producto', verbose_name='Producto'),
        ),
        migrations.AddConstraint(
            model_name='carritoitem',
            constraint=models.UniqueConstraint(fields=('carrito', 'producto'), name='unique_carrito_producto'),
        ),
        migrations.AddConstraint(
            model_name='carritoitem',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='chk_carrito_item_cantidad_positiva'),
        ),
    ]
