# Generated by Django 6.1.1 on 2026-09-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='Enlace HTTP/HTTPS a imagen del producto si no se sube archivo local.', max_length=500, null=True, verbose_name='URL de Imagen Externa'),
        ),
    ]
