# Generated by Django 5.2.17 on 2026-09-30 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0002_producto_imagen_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="especificaciones",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Diccionario de especificaciones técnicas clave-valor del componente",
                verbose_name="Especificaciones Técnicas",
            ),
        ),
    ]
