# Generated by Django 6.1.1 on 2026-10-02 00:35

import django.db.models.deletion
from django.db import migrations, models


def normalizar_especificaciones(apps, schema_editor):
    """Conserva los atributos del JSON antes de retirar su columna original."""
    Producto = apps.get_model('catalogo', 'Producto')
    Especificacion = apps.get_model('catalogo', 'EspecificacionProducto')
    alias = schema_editor.connection.alias
    for producto in Producto.objects.using(alias).iterator():
        if isinstance(producto.especificaciones, dict):
            Especificacion.objects.using(alias).bulk_create([
                Especificacion(producto_id=producto.pk, clave=clave, valor=str(valor))
                for clave, valor in producto.especificaciones.items()
            ])


def restaurar_especificaciones(apps, schema_editor):
    Producto = apps.get_model('catalogo', 'Producto')
    Especificacion = apps.get_model('catalogo', 'EspecificacionProducto')
    alias = schema_editor.connection.alias
    for producto in Producto.objects.using(alias).iterator():
        producto.especificaciones = dict(Especificacion.objects.using(alias).filter(
            producto_id=producto.pk).values_list('clave', 'valor'))
        producto.save(using=alias, update_fields=['especificaciones'])


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_producto_especificaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecificacionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100)),
                ('valor', models.TextField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_tecnicas', to='catalogo.producto')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('producto', 'clave'), name='unique_producto_especificacion')],
            },
        ),
        migrations.RunPython(normalizar_especificaciones, restaurar_especificaciones),
        migrations.RemoveField(model_name='producto', name='especificaciones'),
    ]
